// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> map;
        for(auto x:t){
            map[x]++;
        }
        for(int i=0;i<s.length();i++){
            if(map.find(s[i])!=map.end()) map[s[i]]--;
            if(map[s[i]]==0) map.erase(s[i]);
        }
        return  map.begin()->first;
    }
};